export { default as tour1 } from './tour1.jpg'
export { default as tour11 } from './tour11.jpg'
export { default as tour2 } from './tour2.jpg'
export { default as tour22 } from './tour22.jpg'
export { default as tour3 } from './tour3.jpg'
export { default as tour33 } from './tour33.jpg'